version: 0.2
env:
  secrets-manager:
    SONARCLOUD_ORG: x23293519_Cred:SONAR_ORG
    HOST: x23293519_Cred:SONAR_HOST
    PROJECTKEY: x23293519_Cred:SONAR_PROJECT_KEY
    SONARCLOUD_TOKEN: x23293519_Cred:SONAR_TOKEN

 
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - yum update -y
      - yum install -y jq
      - retry_count=3
      - for i in $(seq 1 $retry_count); do wget https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz && break || sleep 10; done
      - tar xzf apache-maven-3.8.6-bin.tar.gz || true
      - ln -s apache-maven-3.8.6 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip ./sonar-scanner-cli-4.8.0.2856-linux.zip
      - mv sonar-scanner-4.8.0.2856-linux /sonar-scanner
      - export PATH=$PATH:/sonar-scanner/bin/
 
  build:
    commands:
      - find / -name pom.xml -exec mv {} ./pom.xml \; || true
      - mvn sonar:sonar -Dsonar.login=$SONARCLOUD_TOKEN -Dsonar.host.url=$HOST -Dsonar.projectKey=$PROJECTKEY -Dsonar.organization=$SONARCLOUD_ORG
      - sleep 5
      - response_code=$(curl -s -o /dev/null -w "%{http_code}" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=$PROJECTKEY")
      - if [ "$response_code" -ne 200 ]; then
          echo "Quality Gate check failed with HTTP code $response_code";
          exit 1;
        fi
 
artifacts:
  files:
    - '**/*'
    - 'target/*.jar'
    - 'logs/**'