version: 0.2

phases:
  install:
    runtime-versions:
      python: "3.9"
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt pylint
      - yum update -y
      - yum install -y libjpeg-devel zlib-devel
  pre_build:
    commands:
      - pylint $CODEBUILD_SRC_DIR/expense_tracker/* || true
  build:
  commands:
    - echo "Build complete. Listing files:"
    - ls -R
artifacts:
  files:
    - '**/*'
  base-directory: /codebuild/output/src1505004579/src
  